version: '3.8'

services:
  movie-management-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie-management-system
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: unless-stopped
    networks:
      - mms-network

networks:
  mms-network:
    driver: bridge

